### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'LeadingWhite')

### ISSUE THREAD

**Issue by systemGene** [Herrtt/luamin.js#17]
used the example code from the npmjs website
errors with both settings enabled or disabled and also happens to minify and beautify
```js
const Code = `print("hello world!")`
// const Settings = {
//   RenameVariables: true,
//   RenameGlobals: false,
//   SolveMath: true
// }

const Uglified = luamin.Uglify(Code)
console.log(Uglified)
```

full log:
```
        token.LeadingWhite = ''
                           ^

TypeError: Cannot set properties of undefined (setting 'LeadingWhite')
    at stript (C:\Users\no\Desktop\test\node_modules\lua-format\src\luamin.js:2883:28)
    at stripExpr (C:\Users\no\Desktop\test\node_modules\lua-format\src\luamin.js:2929:13)
    at C:\Users\no\Desktop\test\node_modules\lua-format\src\luamin.js:3080:21
    at Array.forEach (<anonymous>)
    at stripStat (C:\Users\no\Desktop\test\node_modules\lua-format\src\luamin.js:3079:31)
    at stripStat (C:\Users\no\Desktop\test\node_modules\lua-format\src\luamin.js:3019:17)
    at StripAst (C:\Users\no\Desktop\test\node_modules\lua-format\src\luamin.js:3259:5)
    at Object.luaminp.Uglify (C:\Users\no\Desktop\test\node_modules\lua-format\src\luamin.js:5312:5)
    at file:///C:/Users/no/Desktop/test/a.js:10:25
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
```

**Comment by systemGene** [comment]
lord herts pls fix
